[package]
name = "prog-wasm-channel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-rs-shared-channel = "0.1.0"
wasm-bindgen = "0.2.79"
