[package]
name = "prog-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
prog = { path = "../prog" }
getrandom = { version = "0.2.5", features = ["js"] }

wasm-bindgen = "0.2.79"
console_error_panic_hook = "0.1.7"
