[package]
name = "prog-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib" ]

[dependencies]
wasm-bindgen = "0.2.79"
prog = { path = ".." }

[dependencies.web-sys]
version = "0.3.56"
features = [
    "HtmlOutputElement",
    "Window",
    "Document"
]
