[package]
name = "prog"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
structopt = "0.3.23"

[dev-dependencies]
pretty_assertions = "0.7.2"
