[package]
name = "prog-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prog = { path = "../prog" }
clap = { version = "3.0.7", features = [ "derive" ] }
