on:
  push:
    branches:
      - trunk
jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./prog
    env:
      RUSTFLAGS: "-C target-feature=+crt-static"
    steps:
    - uses: actions/checkout@v3
    - run: cargo build --release --bin prog-cli
    - uses: actions/upload-artifact@v3
      with:
        name: prog-cli-windows
        path: prog/target/release/prog-cli.exe
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./prog/www
    steps:
      - uses: actions/checkout@v3
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx webpack --mode production
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./prog/www/dist

